# Generated by Django 5.0.2 on 2024-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('conteudo', models.TextField()),
            ],
        ),
    ]
