# Generated by Django 5.0.2 on 2024-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publi',
            name='imagem',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
